Add missing header needed to build on ARM
`make` was failing with this message:

```
$ make
compiling src/pg_query_json_plpgsql.c
In file included from ./src/postgres/include/utils/dsa.h:17,
                 from ./src/postgres/include/nodes/tidbitmap.h:26,
                 from ./src/postgres/include/access/genam.h:19,
                 from ./src/postgres/include/nodes/execnodes.h:17,
                 from ./src/postgres/include/commands/trigger.h:17,
                 from ./src/postgres/include/plpgsql.h:21,
                 from src/pg_query_json_plpgsql.h:5,
                 from src/pg_query_json_plpgsql.c:2:
./src/postgres/include/port/atomics.h:68:10: fatal error: port/atomics/arch-arm.h: No such file or directory
   68 | #include "port/atomics/arch-arm.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Closes https://github.com/lfittl/libpg_query/issues/72