Don't fail builds on systems that have strchrnul support (FreeBSD)
This has to be added as an explicit check because we don't run through
./configure like the regular Postgres source, which would detect this
automatically.

Fixes the following build error on FreeBSD:

src_port_snprintf.c:374:1: error: static declaration of 'strchrnul'
follows non-static declaration
/usr/include/string.h:78:7: note: previous declaration is here